
SELECT C.NAME,M.NAME,SUM(M.PRICE*S.QUANTITY) AS TOTAL_SALES
FROM SALES S
INNER JOIN COUNTRY C ON
C.ID=S.COUNTRY_ID
INNER JOIN CAR_MODEL M ON
M.ID=S.MODEL_ID
WHERE STR_TO_DATE(S.SALES_DATE,'%m/%d/%Y') BETWEEN '2020-01-01' AND '2020-12-31'
GROUP BY C.NAME, M.NAME ORDER BY C.NAME